# Generated by Django 6.0.5 on 2026-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfomodel',
            name='bmr',
            field=models.FloatField(null=True),
        ),
    ]
