# Generated by Django 6.0.4 on 2026-04-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
                ('ofice_number', models.EmailField(max_length=254)),
            ],
        ),
    ]
