# Generated by Django 6.0.4 on 2026-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_departmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='ofice_number',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='office_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
